### ISSUE TITLE
MemoryError！

### ISSUE THREAD

**Issue by ASTurtle** [ngailapdi/LWF#10]
I encounter the numpy memory error while trying to run the code.
My environment:
py3.10 , Torch 1.12.0 , numpy 1.26.1
I have 32GB memory,but the runnning process takes all of it.

Traceback (most recent call last):
  File "D:\WORK\FaultDetection\LWF-master\main.py", line 37, in <module>
    all_train = cifar10(root='./data',
  File "D:\WORK\FaultDetection\LWF-master\data_loader.py", line 45, in __init__
    train_data.append(curr_img/255.)
numpy.core._exceptions.MemoryError: Unable to allocate 1.15 MiB for an array with shape (3, 224, 224) and data type float64

I tried to modify the data type of "curr_img" to float32, but the process failed.

Traceback (most recent call last):
  File "D:\WORK\FaultDetection\LWF-master\main.py", line 37, in <module>
    all_train = cifar10(root='./data',
  File "D:\WORK\FaultDetection\LWF-master\data_loader.py", line 51, in __init__
    self.train_data = np.array(train_data, dtype = np.float32)
numpy.core._exceptions.MemoryError: Unable to allocate 28.0 GiB for an array with shape (50000, 3, 224, 224) and data type float32

What should I do to fix the problem?Should I change my Pytorch and Python to lower versions?

**Comment by kkltdf** [comment]
Hello, I have encountered the same problem. Have you resolved it now?
