### ISSUE TITLE
Excuse me, what should I do with this problem

### ISSUE THREAD

**Issue by zycc853** [ngailapdi/LWF#5]
fatal: Not a valid object name HEAD
Traceback (most recent call last):
  File "C:/Users/Lenovo/Desktop/代码-zy/LWF/6LWF-master/main.py", line 171, in <module>
    githash = subprocess.check_output(['git', 'describe', '--always'])
  File "D:\Programs\Python\Python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "D:\Programs\Python\Python36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe', '--always']' returned non-zero exit status 128.

Excuse me, what should I do with this problem

**Comment by Lyman-Smoker** [comment]
Same error here.Did you find the solution for this?

**Comment by Osstery** [comment]
> Same error here.Did you find the solution for this?

Same here. Any solution now?
